### ISSUE TITLE
How to set acl?

### ISSUE THREAD

**Issue by matteopedani** [gitphill/ldap-alpine#3]
I don't find the right way to set acl usind this ldap docker image?

**Comment by gitphill** [comment]
You can define access control in the slapd.conf file.

I've added an environment variable to make this easy. It's called ACCESS_CONTROL and you set it like so:

```
docker run -t -p 389:389 \
  -e ACCESS_CONTROL="access to * by self write by anonymous auth by users read" \
  pgarrett/ldap-alpine
```

This will allow the user to modify their entry, allows anonymous to authenticate against these entries,
and allows all others to read these entries.

The default is `access to * by * read` which allows anyone and everyone to read anything.

You can find more information on access control here: https://www.openldap.org/doc/admin24/access-control.html

Hope this helps :)
